# Generated by Django 3.2.6 on 2021-08-21 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_companypost_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.UUIDField(default=lib.base_model.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('slug', models.SlugField(default=lib.base_model.random_number_gen, editable=False)),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('company_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company_post')},
            },
        ),
        migrations.CreateModel(
            name='JobRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=lib.base_model.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('attachment', models.FileField(upload_to='')),
                ('job_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
    ]
